from __future__ import annotations

from backend.agents.base_agent import BaseAgent
from backend.graph.state import PipelineState
from backend.models.schemas import GeneratedTest, TestExecutionResult

MODEL = "claude-haiku-4-5-20251001"

SYSTEM_PROMPT = """\
You are a technical writer. Write a concise GitHub PR comment summarising automated test results.

Format requirements:
- Use GitHub-flavoured markdown
- Start with a status badge line: ✅ All tests passed / ❌ Tests failed / ⚠️ Partial failures
- Include a summary table with columns: Test File | Type | Passed | Failed | Status
- Include a Risk Assessment section (level + key reasons)
- Include a Coverage section (estimated delta from test_strategy)
- If any tests need human review, list them under "⚠️ Needs Review"
- End with a Recommendation line: **Recommendation:** Safe to merge / Needs review / Block merge
- Footer: `---\\n🤖 Generated by [TestPilot AI](https://github.com/testpilot-ai)`
- Keep total length under 600 words
- Do NOT include the raw test code\
"""


class PRSummarizerAgent(BaseAgent):
    def __init__(self) -> None:
        super().__init__(model_name=MODEL, agent_name="pr_summarizer")

    async def _execute(
        self, state: PipelineState
    ) -> tuple[PipelineState, int, int]:
        risk_level = state.get("risk_level", "unknown")
        risk_score = state.get("risk_score", 0.0)
        risk_reasons = state.get("risk_reasons", [])
        strategy = state.get("test_strategy", {})
        generated: list[GeneratedTest] = state.get("generated_tests", [])
        results: list[TestExecutionResult] = state.get("execution_results", [])
        repair_attempts = state.get("repair_attempts", 0)
        diagnoses = state.get("repair_diagnosis", [])
        errors = state.get("errors", [])
        pr_url = state.get("pr_url", "")

        total_pass = sum(r.pass_count for r in results)
        total_fail = sum(r.fail_count for r in results)
        all_passed = bool(results) and all(r.success for r in results)

        result_rows = "\n".join(
            f"  {r.file_path} | "
            f"{'unit' if 'unit' in r.file_path else 'integration' if 'integration' in r.file_path else 'api'} | "
            f"{r.pass_count} | {r.fail_count} | {'✅' if r.success else '❌'}"
            for r in results
        ) or "  (no results)"

        context = f"""\
PR URL: {pr_url}
Risk level: {risk_level} (score: {risk_score:.0f}/100)
Risk reasons: {'; '.join(risk_reasons) or 'none'}
Coverage target: {strategy.get('coverage_target', 'N/A')}%
Strategy rationale: {strategy.get('rationale', 'N/A')}

Tests generated: {len(generated)} file(s)
Types: {', '.join(sorted(set(t.test_type for t in generated))) or 'none'}
Execution results:
{result_rows}
Total: {total_pass} passed, {total_fail} failed
All passing: {all_passed}
Repair cycles used: {repair_attempts}/3
Repair diagnoses: {diagnoses}
Pipeline errors: {errors or 'none'}"""

        text, input_tokens, output_tokens = await self._call_llm(
            messages=[{"role": "user", "content": context}],
            system=SYSTEM_PROMPT,
            max_tokens=1500,
        )

        return {**state, "final_summary": text}, input_tokens, output_tokens
